title: Flexa Group Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.flexagroup.co.uk
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#D70040"
  systems:
    - name: API
      category: Uncategorized
    - name: Backend
      category: Uncategorized
    - name: Gateway
      category: Uncategorized
    - name: Front End
      category: Uncategorized
    - name: Core Functionality
      category: Uncategorized
    - name: Framework
      category: Website
    - name: Payment System
      category: Website
    - name: Live Updates
      category: Website
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#3d96d9"
  enableLastMod: true
  headerTextColor: black
  logo: /img/flexa_logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Discord
      link: https://discord.flexagroup.co.uk
    - name: Documentation
      link: https://docs.flexagroup.co.uk
    - name: Website
      link: https://flexagroup.co.uk
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#FFC000"
  notice: "#1155cc"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      untitled: true
    - name: Website
      closed: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
